# Generated by Django 4.2 on 2023-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="rate",
            field=models.IntegerField(default=0),
        ),
    ]
